### ISSUE TITLE
Cannot send Xiaomi S12 vacuum to specific location on map – xiaomi_miio.vacuum_goto service not found

### ISSUE THREAD

**Issue by ByteBand1t** [Nicooow/HA-custom-components-Xiaomi-Cloud-Map-Extractor-Ijai-Support-V3#4]
### Checklist

- [x] I have updated the integration to the latest version available
- [x] I have checked if the problem is already reported

### The problem

Hi there,

First of all, thanks for the work on this integration!
I'm currently using Home Assistant with my Xiaomi S12 vacuum, and while I'm able to see the map in the Lovelace card, the functionality is quite limited beyond that.

**The issues I'm experiencing:**

- The live location of the vacuum is not visible on the map.

- I am unable to send the vacuum to a specific room or location using the map.

- When I try to send the vacuum somewhere on the map, I get the following error:
 `Failed to call service: Service xiaomi_miio.vacuum_goto not found`

### What version of an integration has described problem?

v3.0.0-alpha-3-ijai-2

### What vacuum model do you have problems with?

xiaomi.vacuum.b106eu

### What version of Home Assistant do you use?

2025.4.3

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.0.11
    token: 12345678
    username: mail@mail.com
    password: password
    store_map_raw: true
    store_map_image: true
    store_map_path: /config/vacuum
    draw: ['all']
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell

```
